# Language configuration for helix
#
#
[[language]]
name = "rust"
auto-format = true

roots = ["Cargo.toml", "Cargo.lock"]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[language-server.rust-analyzer]
command = "rust-analyzer"
